spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service
server:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
