spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
